version: '3.7'
services:
  web:
      container_name: $WEB_CONTAINER_NAME
      build: ./nginx
      volumes:
      - ../:/app:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
      - "${WEB_PORT}:80"
      networks:
      - web-network
  php:
      container_name: $PHP_CONTAINER_NAME
      build:
          context: ./php
          dockerfile: Dockerfile
          args:
              buildno: 1
      env_file: .env
      user: www-data:www-data
      volumes:
      - ../:/app:delegated
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      networks:
      - web-network
  db:
      container_name: $DB_CONTAINER_NAME
      build: ./postgresql
      #restart: always
      ports:
      - "${DB_PORT}:5432"
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        DB_SCHEMA: ${DB_SCHEMA}
      volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
      networks:
      - web-network
  redis:
    container_name: $REDIS_CONTAINER_NAME
    image: redis:alpine
    ports:
    - "${REDIS_PORT}:6379"
    networks:
    - web-network
networks:
    web-network: